
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: express-app-container-typingGame
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app # Mount ./server directory to /app in container
      - /app/node_modules # Prevent overwriting node_modules inside container
    environment:
      - NODE_ENV=development
    restart: unless-stopped

  app:
    build:
      context: ./typingGame
      dockerfile: Dockerfile
    container_name: typingGame-Vite
    ports:
      - "5173:5173"
    volumes:
      - ./typingGame:/app # Mount ./typing_app directory to /app in container
      - /app/node_modules # Prevent overwriting node_modules inside container
    environment:
      - NODE_ENV=development
    restart: unless-stopped